// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDeploymentSops) DeepCopyInto(out *ConfigDeploymentSops) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDeploymentSops.
func (in *ConfigDeploymentSops) DeepCopy() *ConfigDeploymentSops {
	if in == nil {
		return nil
	}
	out := new(ConfigDeploymentSops)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigDeploymentSops) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDeploymentSopsList) DeepCopyInto(out *ConfigDeploymentSopsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigDeploymentSops, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDeploymentSopsList.
func (in *ConfigDeploymentSopsList) DeepCopy() *ConfigDeploymentSopsList {
	if in == nil {
		return nil
	}
	out := new(ConfigDeploymentSopsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigDeploymentSopsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDeploymentSopsSpec) DeepCopyInto(out *ConfigDeploymentSopsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDeploymentSopsSpec.
func (in *ConfigDeploymentSopsSpec) DeepCopy() *ConfigDeploymentSopsSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigDeploymentSopsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDeploymentSopsStatus) DeepCopyInto(out *ConfigDeploymentSopsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDeploymentSopsStatus.
func (in *ConfigDeploymentSopsStatus) DeepCopy() *ConfigDeploymentSopsStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigDeploymentSopsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigIngressSops) DeepCopyInto(out *ConfigIngressSops) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigIngressSops.
func (in *ConfigIngressSops) DeepCopy() *ConfigIngressSops {
	if in == nil {
		return nil
	}
	out := new(ConfigIngressSops)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigIngressSops) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigIngressSopsList) DeepCopyInto(out *ConfigIngressSopsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigIngressSops, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigIngressSopsList.
func (in *ConfigIngressSopsList) DeepCopy() *ConfigIngressSopsList {
	if in == nil {
		return nil
	}
	out := new(ConfigIngressSopsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigIngressSopsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigIngressSopsSpec) DeepCopyInto(out *ConfigIngressSopsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigIngressSopsSpec.
func (in *ConfigIngressSopsSpec) DeepCopy() *ConfigIngressSopsSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigIngressSopsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigIngressSopsStatus) DeepCopyInto(out *ConfigIngressSopsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigIngressSopsStatus.
func (in *ConfigIngressSopsStatus) DeepCopy() *ConfigIngressSopsStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigIngressSopsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigServiceSops) DeepCopyInto(out *ConfigServiceSops) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigServiceSops.
func (in *ConfigServiceSops) DeepCopy() *ConfigServiceSops {
	if in == nil {
		return nil
	}
	out := new(ConfigServiceSops)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigServiceSops) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigServiceSopsList) DeepCopyInto(out *ConfigServiceSopsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigServiceSops, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigServiceSopsList.
func (in *ConfigServiceSopsList) DeepCopy() *ConfigServiceSopsList {
	if in == nil {
		return nil
	}
	out := new(ConfigServiceSopsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigServiceSopsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigServiceSopsSpec) DeepCopyInto(out *ConfigServiceSopsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigServiceSopsSpec.
func (in *ConfigServiceSopsSpec) DeepCopy() *ConfigServiceSopsSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigServiceSopsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigServiceSopsStatus) DeepCopyInto(out *ConfigServiceSopsStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigServiceSopsStatus.
func (in *ConfigServiceSopsStatus) DeepCopy() *ConfigServiceSopsStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigServiceSopsStatus)
	in.DeepCopyInto(out)
	return out
}
